baseURL = "https://saadfakhreddine.github.io/"
languageCode = "en-us"
title = "Saad Labs"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowBreadCrumbs = true
  env = "production"
  disableAnalytics = true
  homeInfoParams = false
  mainSections = ["posts"]


[outputs]
  home = ["HTML", "RSS", "JSON"]

