baseURL = "https://saadfakhreddine.github.io/"
languageCode = "en-us"
title = "My Hugo Blog"
theme = "PaperMod"

[params]
  ShowReadingTime = true
  ShowBreadCrumbs = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
